const ESTADO = { OK: 1, ERROR: -1 };

const HTTP = {
  OK: 200,
  CREADO: 201,
  PETICION_INVALIDA: 400,
  NO_AUTORIZADO: 401,
  PROHIBIDO: 403,
  NO_ENCONTRADO: 404,
  CONFLICTO: 409,
  DEMASIADAS_PETICIONES: 429,
  ERROR_INTERNO: 500,
  NO_DISPONIBLE: 503
};

const ESTADOS_CITA = {
  RESERVA_TEMPORAL: 'RESERVA_TEMPORAL',
  PENDIENTE_PAGO: 'PENDIENTE_PAGO',
  CONFIRMADA: 'CONFIRMADA',
  ATENDIDA: 'ATENDIDA',
  CANCELADA: 'CANCELADA',
  NO_ASISTIO: 'NO_ASISTIO',
  EXPIRADA: 'EXPIRADA'
};

const ESTADOS_PAGO = {
  PENDIENTE: 'PENDIENTE',
  EXPIRADO: 'EXPIRADO',
  EN_CONCILIACION: 'EN_CONCILIACION',
  CONFIRMADO: 'CONFIRMADO'
};

const PROVEEDOR_PAGO = { SIMULADOR: 'SIMULADOR', PAYPHONE: 'PAYPHONE' };

const ESTADOS_RESERVA_EXPIRABLES = [ESTADOS_CITA.RESERVA_TEMPORAL, ESTADOS_CITA.PENDIENTE_PAGO];
const ESTADOS_CITA_BLOQUEANTES = [...ESTADOS_RESERVA_EXPIRABLES, ESTADOS_CITA.CONFIRMADA, ESTADOS_CITA.ATENDIDA];

// Cada filtro de la pantalla de agenda y los estados de cita que incluye.
const FILTROS_AGENDA = {
  TODAS: [
    ESTADOS_CITA.RESERVA_TEMPORAL,
    ESTADOS_CITA.PENDIENTE_PAGO,
    ESTADOS_CITA.CONFIRMADA,
    ESTADOS_CITA.ATENDIDA
  ],
  CONFIRMADAS: [ESTADOS_CITA.CONFIRMADA],
  PENDIENTES: [ESTADOS_CITA.RESERVA_TEMPORAL, ESTADOS_CITA.PENDIENTE_PAGO],
  ATENDIDAS: [ESTADOS_CITA.ATENDIDA],
  CANCELADAS: [ESTADOS_CITA.CANCELADA, ESTADOS_CITA.NO_ASISTIO, ESTADOS_CITA.EXPIRADA]
};

const DIAS_SEMANA = { 1: 'LUNES', 2: 'MARTES', 3: 'MIERCOLES', 4: 'JUEVES', 5: 'VIERNES', 6: 'SABADO', 7: 'DOMINGO' };

module.exports = {
  ESTADO,
  HTTP,
  ESTADOS_CITA,
  ESTADOS_PAGO,
  PROVEEDOR_PAGO,
  ESTADOS_RESERVA_EXPIRABLES,
  ESTADOS_CITA_BLOQUEANTES,
  DIAS_SEMANA,
  ZONA_HORARIA_DEFECTO: 'America/Guayaquil',
  MONEDA_DEFECTO: 'USD',
  PREFIJO_REFERENCIA_COBRO: 'AGI-',
  BANCO_SIMULADOR: 'SIMULADOR',
  LOCK_PROFESIONAL: 714215,
  INTERVALO_REVISION_RESERVAS_MS: 60 * 1000,
  MINUTOS_RESERVA: { DEFECTO: 15, MIN: 1, MAX: 60 },
  DISPONIBILIDAD: { DIAS_DEFECTO: 7, DIAS_MIN: 1, DIAS_MAX: 30 },
  LONGITUD_MAX: { TEXTO: 150, REFERENCIA: 80, NOMBRE: 100, TELEFONO: 30, DIRECCION: 300 },
  PORCENTAJE_ANTICIPO_COMPLETO: 100,
  PUNTAJE_CONCILIACION: { COINCIDE: 100, REVISION: 50 },
  HEADER_SECRETO_SIMULADOR: 'x-pago-simulador-secreto',
  TIPOS_EXCEPCION: { BLOQUEO: 'BLOQUEO', DISPONIBILIDAD_EXTRA: 'DISPONIBILIDAD_EXTRA' },
  TRANSACCION_OPCIONES: { maxWait: 10000, timeout: 20000 },
  METODO_PAGO: { PASARELA: 'PASARELA' },
  ORIGEN_TRANSACCION: { PASARELA: 'PASARELA' },
  ESTADOS_CONCILIACION: { COINCIDENCIA_AUTOMATICA: 'COINCIDENCIA_AUTOMATICA', REVISION_MANUAL: 'REVISION_MANUAL' },
    RESULTADO_EVENTO: {
    EVENTO_YA_PROCESADO: 'EVENTO_YA_PROCESADO',
    MONTO_EN_REVISION: 'MONTO_EN_REVISION',
    PAGO_YA_CONFIRMADO: 'PAGO_YA_CONFIRMADO',
    PAGO_TARDIO_SIN_CITA_CONFIRMADA: 'PAGO_TARDIO_SIN_CITA_CONFIRMADA',
    CITA_CONFIRMADA: 'CITA_CONFIRMADA'
  },
  LIMITES: {
    GENERAL: { ventanaMs: 60 * 1000, maximo: 300 },
    ESCRITURA: { ventanaMs: 60 * 1000, maximo: 30},
    AUTENTICACION: { ventanaMs: 15 * 60 * 1000, maximo: 20 }
  },
  TIPO_ACCESO: {
    SUPER_ADMIN: 'SUPER_ADMIN',
    ADMIN_EMPRESA: 'ADMIN_EMPRESA',
    PERSONAL: 'PERSONAL',
    CLIENTE: 'CLIENTE'
  },
  ALCANCE_ROL: { ORGANIZACION: 'ORGANIZACION', PROPIO: 'PROPIO' },
  AUTH: {
    PROVEEDORES: { LOCAL: 'local', KEYCLOAK: 'keycloak' },
    TIPO_TOKEN: 'Bearer',
    ACCESS_EXPIRA: '15m',
    ACCESS_EXPIRA_SEGUNDOS: 900,
    REFRESH_DIAS: 30,
    BCRYPT_RONDAS: 12,
    MAX_INTENTOS_FALLIDOS: 5,
    BLOQUEO_MINUTOS: 15,
    CLAVE_MIN_LARGO: 8
  },
  AGENDA: { FILTROS: FILTROS_AGENDA, FILTRO_DEFECTO: 'TODAS', MAX_DIAS_RANGO: 31 },
  PAGINACION: { PAGINA_DEFECTO: 1, TAMANO_DEFECTO: 20, TAMANO_MAX: 100 },
};
