const ESTADO = { OK: 1, ERROR: -1 };

const HTTP = {
  OK: 200,
  CREADO: 201,
  PETICION_INVALIDA: 400,
  NO_AUTORIZADO: 401,
  PROHIBIDO: 403,
  NO_ENCONTRADO: 404,
  CONFLICTO: 409,
  DEMASIADAS_PETICIONES: 429,
  ERROR_INTERNO: 500,
  NO_DISPONIBLE: 503
};

const ESTADOS_CITA = {
  RESERVA_TEMPORAL: 'RESERVA_TEMPORAL',
  PENDIENTE_PAGO: 'PENDIENTE_PAGO',
  CONFIRMADA: 'CONFIRMADA',
  ATENDIDA: 'ATENDIDA',
  CANCELADA: 'CANCELADA',
  NO_ASISTIO: 'NO_ASISTIO',
  EXPIRADA: 'EXPIRADA'
};

const ESTADOS_PAGO = {
  PENDIENTE: 'PENDIENTE',
  EXPIRADO: 'EXPIRADO',
  EN_CONCILIACION: 'EN_CONCILIACION',
  CONFIRMADO: 'CONFIRMADO'
};

const PROVEEDOR_PAGO = { SIMULADOR: 'SIMULADOR', PAYPHONE: 'PAYPHONE' };

const ESTADOS_RESERVA_EXPIRABLES = [ESTADOS_CITA.RESERVA_TEMPORAL, ESTADOS_CITA.PENDIENTE_PAGO];
const ESTADOS_CITA_BLOQUEANTES = [...ESTADOS_RESERVA_EXPIRABLES, ESTADOS_CITA.CONFIRMADA, ESTADOS_CITA.ATENDIDA];

// Cada filtro de la pantalla de agenda y los estados de cita que incluye.
const FILTROS_AGENDA = {
  TODAS: [
    ESTADOS_CITA.RESERVA_TEMPORAL,
    ESTADOS_CITA.PENDIENTE_PAGO,
    ESTADOS_CITA.CONFIRMADA,
    ESTADOS_CITA.ATENDIDA
  ],
  CONFIRMADAS: [ESTADOS_CITA.CONFIRMADA],
  PENDIENTES: [ESTADOS_CITA.RESERVA_TEMPORAL, ESTADOS_CITA.PENDIENTE_PAGO],
  ATENDIDAS: [ESTADOS_CITA.ATENDIDA],
  CANCELADAS: [ESTADOS_CITA.CANCELADA, ESTADOS_CITA.NO_ASISTIO, ESTADOS_CITA.EXPIRADA]
};

const DIAS_SEMANA = { 1: 'LUNES', 2: 'MARTES', 3: 'MIERCOLES', 4: 'JUEVES', 5: 'VIERNES', 6: 'SABADO', 7: 'DOMINGO' };

module.exports = {
  ESTADO,
  HTTP,
  ESTADOS_CITA,
  ESTADOS_PAGO,
  PROVEEDOR_PAGO,
  ESTADOS_RESERVA_EXPIRABLES,
  ESTADOS_CITA_BLOQUEANTES,
  DIAS_SEMANA,
  ZONA_HORARIA_DEFECTO: 'America/Guayaquil',
  MONEDA_DEFECTO: 'USD',
  PREFIJO_REFERENCIA_COBRO: 'AGI-',
  BANCO_SIMULADOR: 'SIMULADOR',
  LOCK_PROFESIONAL: 714215,
  INTERVALO_REVISION_RESERVAS_MS: 60 * 1000,
  MINUTOS_RESERVA: { DEFECTO: 15, MIN: 1, MAX: 60 },
  DISPONIBILIDAD: { DIAS_DEFECTO: 7, DIAS_MIN: 1, DIAS_MAX: 30 },
  LONGITUD_MAX: { TEXTO: 150, REFERENCIA: 80, NOMBRE: 100, TELEFONO: 30, DIRECCION: 300 },
  PORCENTAJE_ANTICIPO_COMPLETO: 100,
  PUNTAJE_CONCILIACION: { COINCIDE: 100, REVISION: 50 },
  HEADER_SECRETO_SIMULADOR: 'x-pago-simulador-secreto',
  TIPOS_EXCEPCION: { BLOQUEO: 'BLOQUEO', DISPONIBILIDAD_EXTRA: 'DISPONIBILIDAD_EXTRA' },
  TRANSACCION_OPCIONES: { maxWait: 10000, timeout: 20000 },
  METODO_PAGO: { PASARELA: 'PASARELA' },
  ORIGEN_TRANSACCION: { PASARELA: 'PASARELA' },
  ESTADOS_CONCILIACION: { COINCIDENCIA_AUTOMATICA: 'COINCIDENCIA_AUTOMATICA', REVISION_MANUAL: 'REVISION_MANUAL' },
    RESULTADO_EVENTO: {
    EVENTO_YA_PROCESADO: 'EVENTO_YA_PROCESADO',
    MONTO_EN_REVISION: 'MONTO_EN_REVISION',
    PAGO_YA_CONFIRMADO: 'PAGO_YA_CONFIRMADO',
    PAGO_TARDIO_SIN_CITA_CONFIRMADA: 'PAGO_TARDIO_SIN_CITA_CONFIRMADA',
    CITA_CONFIRMADA: 'CITA_CONFIRMADA'
  },
  LIMITES: {
    GENERAL: { ventanaMs: 60 * 1000, maximo: 300 },
    ESCRITURA: { ventanaMs: 60 * 1000, maximo: 30},
    AUTENTICACION: { ventanaMs: 15 * 60 * 1000, maximo: 20 }
  },
  TIPO_ACCESO: {
    SUPER_ADMIN: 'SUPER_ADMIN',
    ADMIN_EMPRESA: 'ADMIN_EMPRESA',
    PERSONAL: 'PERSONAL',
    CLIENTE: 'CLIENTE'
  },
  ALCANCE_ROL: { ORGANIZACION: 'ORGANIZACION', PROPIO: 'PROPIO' },
  AUTH: {
    PROVEEDORES: { LOCAL: 'local', KEYCLOAK: 'keycloak' },
    TIPO_TOKEN: 'Bearer',
    ACCESS_EXPIRA: '15m',
    ACCESS_EXPIRA_SEGUNDOS: 900,
    REFRESH_DIAS: 30,
    BCRYPT_RONDAS: 12,
    MAX_INTENTOS_FALLIDOS: 5,
    BLOQUEO_MINUTOS: 15,
    CLAVE_MIN_LARGO: 8,
    CLAVE_TEMPORAL_LARGO: 12
  },
  // Envío de correos: CORREO_PROVEEDOR en el .env (ninguno | smtp).
  CORREO: { PROVEEDORES: { NINGUNO: 'ninguno', SMTP: 'smtp' } },
  AGENDA: { FILTROS: FILTROS_AGENDA, FILTRO_DEFECTO: 'TODAS', MAX_DIAS_RANGO: 31 },
  PAGINACION: { PAGINA_DEFECTO: 1, TAMANO_DEFECTO: 20, TAMANO_MAX: 100 },
  // Formatos de la configuración de módulos. La ruta tiene un solo segmento porque el
  // front carga el feature cuya carpeta se llama igual (ej. /historia-clinica).
  FORMATOS_ACCESO: {
    CODIGO: /^[A-Z][A-Z0-9_]*$/,
    RUTA: /^\/[a-z0-9]+(-[a-z0-9]+)*$/,
    ICONO: /^[a-z0-9]+(-[a-z0-9]+)*$/,
    CODIGO_BOTON: /^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/
  },
  // Largos de las columnas en schema.prisma (modulos, pantallas y permisos).
  LONGITUD_ACCESO: {
    CODIGO_MODULO: 60,
    CODIGO_PANTALLA: 80,
    CODIGO_BOTON: 80,
    NOMBRE: 100,
    DESCRIPCION: 250,
    ICONO: 60,
    RUTA: 150,
    CATEGORIA: 50
  },
  ORDEN_ACCESO: { MIN: 0, MAX: 999 },
  // Catálogos genéricos que usa el código (sus items se administran en la pantalla Catálogos).
  CATALOGOS: {
    BANCOS: 'BANCOS',
    BILLETERAS: 'BILLETERAS',
    TIPOS_CUENTA: 'TIPOS_CUENTA',
    TIPOS_DOCUMENTO: 'TIPOS_DOCUMENTO'
  },
  LONGITUD_CATALOGOS: { CODIGO: 60, NOMBRE: 150, DESCRIPCION: 250 },
  // Items de TIPOS_DOCUMENTO y qué archivos acepta cada uno.
  TIPOS_DOCUMENTO: { QR_COBRO: 'QR_COBRO', COMPROBANTE_PAGO: 'COMPROBANTE_PAGO' },
  // Archivos permitidos: extensión y firma (primeros bytes) para no confiar en el nombre ni en el
  // tipo que declara el navegador.
  ARCHIVOS_PERMITIDOS: {
    'image/png': { extension: 'png', firma: [0x89, 0x50, 0x4e, 0x47] },
    'image/jpeg': { extension: 'jpg', firma: [0xff, 0xd8, 0xff] },
    'application/pdf': { extension: 'pdf', firma: [0x25, 0x50, 0x44, 0x46] }
  },
  MIME_POR_TIPO_DOCUMENTO: {
    QR_COBRO: ['image/png', 'image/jpeg'],
    COMPROBANTE_PAGO: ['image/png', 'image/jpeg', 'application/pdf']
  },
  LONGITUD_DOCUMENTOS: { NOMBRE_ORIGINAL: 255 },
  // Enum TipoMedioCobro de schema.prisma.
  TIPOS_MEDIO_COBRO: { TRANSFERENCIA: 'TRANSFERENCIA', BILLETERA: 'BILLETERA' },
  LONGITUD_COBROS: { NUMERO: 40, TITULAR: 150, IDENTIFICACION: 20, ALIAS: 100 },
  // Enum TipoReserva de schema.prisma: qué reserva el cliente en un tipo de negocio.
  TIPOS_RESERVA: { PERSONAS: 'PERSONAS', ESPACIOS: 'ESPACIOS', AMBOS: 'AMBOS' },
  // Largos de categorias_empresa, cargos y usuarios.cargo_observacion en schema.prisma.
  LONGITUD_CATEGORIAS: { CODIGO: 60, NOMBRE: 100, DESCRIPCION: 250, ICONO: 60, OBSERVACION_CARGO: 250 },
  // Enums de schema.prisma (EstadoSuscripcion, Periodicidad).
  ESTADOS_SUSCRIPCION: { PENDIENTE_PAGO: 'PENDIENTE_PAGO', VIGENTE: 'VIGENTE', FINALIZADA: 'FINALIZADA' },
  PERIODICIDADES: { MENSUAL: 'MENSUAL', ANUAL: 'ANUAL' },
  // Cómo se cobra una suscripción o un módulo suelto. Hoy no hay pasarela: se activa al contratar.
  PROVEEDOR_COBRO: { SIN_PASARELA: 'SIN_PASARELA' },
  // Venta de planes y módulos sueltos. Largos según schema.prisma (planes).
  VENTA: {
    PRECIO_MIN: 0,
    PRECIO_MAX: 99999999.99,
    FORMATO_MONEDA: /^[A-Z]{3}$/,
    LONGITUD_CODIGO_PLAN: 40,
    LONGITUD_NOMBRE_PLAN: 100,
    LONGITUD_DESCRIPCION_PLAN: 500,
    MODULOS_POR_PLAN_MAX: 100
  },
};
