const ESTADO = { OK: 1, ERROR: -1 };

const HTTP = {
  OK: 200,
  CREADO: 201,
  PETICION_INVALIDA: 400,
  NO_AUTORIZADO: 401,
  PROHIBIDO: 403,
  NO_ENCONTRADO: 404,
  CONFLICTO: 409,
  ERROR_INTERNO: 500,
  NO_DISPONIBLE: 503
};

const ESTADOS_CITA = {
  RESERVA_TEMPORAL: 'RESERVA_TEMPORAL',
  PENDIENTE_PAGO: 'PENDIENTE_PAGO',
  CONFIRMADA: 'CONFIRMADA',
  ATENDIDA: 'ATENDIDA',
  CANCELADA: 'CANCELADA',
  NO_ASISTIO: 'NO_ASISTIO',
  EXPIRADA: 'EXPIRADA'
};

const ESTADOS_PAGO = {
  PENDIENTE: 'PENDIENTE',
  EXPIRADO: 'EXPIRADO',
  EN_CONCILIACION: 'EN_CONCILIACION',
  CONFIRMADO: 'CONFIRMADO'
};

const PROVEEDOR_PAGO = { SIMULADOR: 'SIMULADOR', PAYPHONE: 'PAYPHONE' };

const ESTADOS_RESERVA_EXPIRABLES = [ESTADOS_CITA.RESERVA_TEMPORAL, ESTADOS_CITA.PENDIENTE_PAGO];
const ESTADOS_CITA_BLOQUEANTES = [...ESTADOS_RESERVA_EXPIRABLES, ESTADOS_CITA.CONFIRMADA, ESTADOS_CITA.ATENDIDA];

const DIAS_SEMANA = { 1: 'LUNES', 2: 'MARTES', 3: 'MIERCOLES', 4: 'JUEVES', 5: 'VIERNES', 6: 'SABADO', 7: 'DOMINGO' };

module.exports = {
  ESTADO,
  HTTP,
  ESTADOS_CITA,
  ESTADOS_PAGO,
  PROVEEDOR_PAGO,
  ESTADOS_RESERVA_EXPIRABLES,
  ESTADOS_CITA_BLOQUEANTES,
  DIAS_SEMANA,
  ZONA_HORARIA_DEFECTO: 'America/Guayaquil',
  MONEDA_DEFECTO: 'USD',
  PREFIJO_REFERENCIA_COBRO: 'AGI-',
  BANCO_SIMULADOR: 'SIMULADOR',
  LOCK_PROFESIONAL: 714215,
  INTERVALO_REVISION_RESERVAS_MS: 60 * 1000,
  MINUTOS_RESERVA: { DEFECTO: 15, MIN: 1, MAX: 60 },
  DISPONIBILIDAD: { DIAS_DEFECTO: 7, DIAS_MIN: 1, DIAS_MAX: 30 },
  LONGITUD_MAX: { TEXTO: 150, REFERENCIA: 80, NOMBRE: 100, TELEFONO: 30, DIRECCION: 300 },
  PORCENTAJE_ANTICIPO_COMPLETO: 100,
  PUNTAJE_CONCILIACION: { COINCIDE: 100, REVISION: 50 },
  HEADER_SECRETO_SIMULADOR: 'x-pago-simulador-secreto'
};