module.exports = {
  // Genéricos
  ERROR_GENERICO: 'Ocurrió un error',
  ERROR_INTERNO: 'Error interno del servidor',
  JSON_INVALIDO: 'El cuerpo de la petición no es un JSON válido',
  REGISTRO_DUPLICADO: 'Ya existe un registro con esos datos',
  REGISTRO_NO_ENCONTRADO: 'El registro solicitado no existe',
  ID_INVALIDO: (campo) => `${campo} debe ser un entero positivo`,
  DATO_INVALIDO: (campo) => `${campo} no es válido`,
  CAMPO_OBLIGATORIO: (campo) => `${campo} es obligatorio`,

  // Clientes y organización
  ORGANIZACION_NO_ENCONTRADA: 'Organización no encontrada',
  CLIENTES_OK: 'Clientes obtenidos correctamente',
  CLIENTE_REGISTRADO: 'Cliente registrado correctamente',
  CLIENTE_EXISTENTE: 'El cliente ya estaba registrado',
  CLIENTE_NO_ENCONTRADO: 'Cliente no encontrado en esta organización',

  // Profesionales y servicios
  PROFESIONAL_NO_ENCONTRADO: 'Profesional no encontrado',
  SERVICIO_NO_OFRECIDO: 'El profesional no ofrece ese servicio',
  SERVICIOS_OK: 'Servicios obtenidos correctamente',

  // Disponibilidad
  FECHA_DESDE_INVALIDA: 'La fecha desde no es válida',
  DISPONIBILIDAD_OK: 'Disponibilidad obtenida correctamente',

  // Canal
  CANAL_NO_ENCONTRADO: 'Canal de atención no encontrado',
  CANAL_NO_DISPONIBLE: 'Canal de atención no disponible',
  CANAL_INACTIVO: 'El canal de atención está inactivo',
  ORGANIZACION_INACTIVA: 'La organización asociada al canal está inactiva',
  PROFESIONAL_INACTIVO: 'El profesional asociado al canal está inactivo',

  // Reservas
  FECHA_INICIO_SIN_ZONA: 'fecha_inicio debe ser ISO 8601 y contener zona horaria',
  FECHA_PASADA: 'El horario debe ser futuro',
  HORARIO_NO_DISPONIBLE: 'Ese horario ya no está disponible. Consulta otro horario.',
  RESERVA_CREADA: 'Reserva temporal creada. Aún no es una cita confirmada.',
  RESERVA_EXISTENTE: 'Ya existe una reserva temporal vigente para ese horario.',

  // Pagos
  MONTO_INVALIDO: 'monto debe ser un número positivo',
  PAGO_PREVIO_NO_REQUERIDO: 'Este servicio no requiere pago previo',
  CITA_NO_ENCONTRADA: 'Reserva no encontrada para este canal',
  CITA_YA_CONFIRMADA: 'La cita ya está confirmada',
  RESERVA_EXPIRADA: 'La reserva temporal ya expiró',
  CITA_NO_PUEDE_PAGAR: 'La cita no puede iniciar un pago',
  REFERENCIA_NO_ENCONTRADA: 'La referencia de cobro no existe',
  PAGO_CREADO: 'Solicitud de pago creada en modo simulador.',
  PAGO_EXISTENTE: 'Ya existe una solicitud de pago vigente para esta reserva.',
  ESTADO_RESERVA_PAGO_OK: 'Estado de reserva y pago obtenido correctamente.',

  // Webhook del simulador
  SIMULADOR_NO_DISPONIBLE: 'El simulador de pagos no está disponible en producción',
  SIMULADOR_SIN_CONFIGURAR: 'Configura PAGO_SIMULADOR_SECRETO para usar el simulador',
  WEBHOOK_NO_AUTORIZADO: 'El secreto del simulador no es válido',
  SERVICIO_OK: 'Servicio obtenido correctamente',
  CONTEXTO_OK: 'Contexto del canal obtenido correctamente',
  FECHA_INICIO_INVALIDA: 'fecha_inicio no es válida',
  OBSERVACION_PAGO_CONFIRMADO: 'Pago confirmado por el simulador local.',
  OBSERVACION_MONTO_DISTINTO: 'El monto recibido no coincide con el monto esperado.',
  EVENTO_PAGO_PROCESADO: 'Evento de pago procesado',
  DEMASIADAS_PETICIONES: 'Demasiadas peticiones, intenta de nuevo en un momento',
    // Acceso
  CREDENCIALES_INVALIDAS: 'Credenciales inválidas',
  CUENTA_BLOQUEADA: 'La cuenta está bloqueada temporalmente. Intenta más tarde',
  USUARIO_INACTIVO: 'El usuario está inactivo',
  TOKEN_REQUERIDO: 'Debes iniciar sesión',
  TOKEN_INVALIDO: 'La sesión no es válida o expiró',
  SESION_EXPIRADA: 'La sesión expiró, inicia sesión de nuevo',
  SIN_PERMISO: 'No tienes permiso para realizar esta acción',
  CORREO_YA_REGISTRADO: 'Ya existe una cuenta con ese correo',
  CLAVE_DEBIL: 'La contraseña debe tener al menos 8 caracteres',
  PROVEEDOR_NO_SOPORTADO: 'El proveedor de autenticación configurado no está disponible',
  LOGIN_OK: 'Inicio de sesión correcto',
  SESION_CERRADA: 'Sesión cerrada',
  SESION_RENOVADA: 'Sesión renovada correctamente',
  REGISTRO_OK: 'Cuenta creada correctamente',
  REGISTRO_EMPRESA_OK: 'Empresa y administrador creados correctamente',
  USUARIO_ACTUAL_OK: 'Usuario obtenido correctamente',
  ROL_PLANTILLA_NO_ENCONTRADO: 'Falta el rol base del sistema. Ejecuta el seed de acceso',
  RUC_YA_REGISTRADO: 'Ya existe una empresa con ese RUC',
  IDENTIFICACION_YA_REGISTRADA: 'Ya existe una persona con esa identificación',
  AGENDA_OK: 'Agenda obtenida correctamente',
  SERVICIO_NO_ENCONTRADO: 'Servicio no encontrado',
  SERVICIO_GUARDADO: 'Servicio guardado correctamente',
  SERVICIO_ESTADO_OK: 'Estado del servicio actualizado',
  SERVICIOS_PROPIOS_NO_PERMITIDOS: 'Tu empresa no permite que los profesionales creen servicios',
  SERVICIO_COMPARTIDO: 'Este servicio lo ofrecen otros profesionales; solo el administrador puede modificarlo',
  PRECIOS_PROPIOS_NO_PERMITIDOS: 'Tu empresa no permite precios o duraciones distintas por profesional',

  // Configuración de módulos, pantallas y botones
  CONFIGURACION_MODULOS_OK: 'Configuración de módulos obtenida correctamente',
  MODULO_GUARDADO: 'Módulo guardado correctamente',
  MODULO_ESTADO_OK: 'Estado del módulo actualizado',
  MODULO_NO_ENCONTRADO: 'Módulo no encontrado',
  MODULO_CODIGO_DUPLICADO: 'Ya existe un módulo con ese código',
  MODULO_PROTEGIDO: 'Este módulo contiene la configuración de módulos y no se puede desactivar',
  PANTALLA_GUARDADA: 'Pantalla guardada correctamente',
  PANTALLA_ESTADO_OK: 'Estado de la pantalla actualizado',
  PANTALLA_NO_ENCONTRADA: 'Pantalla no encontrada',
  PANTALLA_CODIGO_DUPLICADO: 'Ya existe una pantalla con ese código',
  PANTALLA_RUTA_DUPLICADA: 'Ya existe una pantalla con esa ruta',
  PANTALLA_PROTEGIDA: 'Esta es la pantalla de configuración de módulos y no se puede desactivar',
  PANTALLA_PROTEGIDA_PLATAFORMA: 'La pantalla de configuración de módulos debe ser solo de plataforma',
  ACCIONES_ASIGNADAS: 'Botones asignados a la pantalla',
  ACCION_NO_ENCONTRADA: 'Alguna de las acciones no existe o está inactiva',
  RUTA_SIN_RECURSO: 'La ruta de la pantalla no permite generar el código de sus botones',
  BOTON_CODIGO_EN_OTRA_PANTALLA: (codigo) => `El botón ${codigo} ya pertenece a otra pantalla`,
  DESCRIPCION_BOTON: (accion, pantalla) => `${accion} en ${pantalla}`,
  BOTON_ELIMINADO: 'Botón eliminado correctamente',
  BOTON_NO_ENCONTRADO: 'Botón no encontrado',
  BOTON_EN_USO: (roles) =>
    `El botón está asignado a ${roles} ${roles === 1 ? 'rol' : 'roles'}; quítalo de los roles antes de eliminarlo`,
  BOTON_DEL_SISTEMA: 'Este botón lo usa el sistema para autorizar acciones y no se puede eliminar',

  // Planes (super admin)
  PLANES_OK: 'Planes obtenidos correctamente',
  PLAN_GUARDADO: 'Plan guardado correctamente',
  PLAN_ESTADO_OK: 'Estado del plan actualizado',
  PLAN_NO_ENCONTRADO: 'Plan no encontrado',
  PLAN_CODIGO_DUPLICADO: 'Ya existe un plan con ese código',
  PLAN_MODULOS_INVALIDOS: 'Algunos módulos no existen, están inactivos o son base (ya los tienen todas las empresas)',
  PRECIO_MODULO_GUARDADO: 'Precio del módulo guardado correctamente',

  // Suscripción de la empresa (administrador de empresa)
  SUSCRIPCION_OK: 'Suscripción obtenida correctamente',
  PLAN_CAMBIADO: (plan) => `Tu empresa ahora tiene el plan ${plan}`,
  PLAN_YA_VIGENTE: 'Tu empresa ya tiene ese plan',
  PLAN_NO_DISPONIBLE: 'Ese plan ya no está disponible',
  MODULO_COMPRADO: (modulo) => `Módulo ${modulo} agregado a tu empresa`,
  MODULO_CANCELADO: (modulo) => `Módulo ${modulo} cancelado`,
  MODULO_NO_VENDIBLE: 'Ese módulo no se vende por separado',
  MODULO_EN_PLAN: 'Ese módulo ya está incluido en tu plan',
  MODULO_YA_CONTRATADO: 'Tu empresa ya tiene ese módulo',
  MODULO_NO_CONTRATADO: 'Tu empresa no tiene ese módulo contratado por separado',

  // Cambio de clave
  CLAVE_CAMBIADA: 'Clave actualizada correctamente',
  CLAVE_ACTUAL_INCORRECTA: 'La clave actual no es correcta',
  CLAVE_IGUAL: 'La nueva clave debe ser distinta de la actual',

  // Roles
  ROLES_OK: 'Roles obtenidos correctamente',
  ROL_GUARDADO: 'Rol guardado correctamente',
  ROL_ESTADO_OK: 'Estado del rol actualizado',
  ROL_NO_ENCONTRADO: 'Rol no encontrado',
  ROL_NO_EDITABLE: 'Este rol no se puede modificar desde aquí',
  ROL_CODIGO_DUPLICADO: 'Ya existe un rol con ese código',
  ROL_PANTALLAS_INVALIDAS: 'Algunas pantallas no están disponibles para tu empresa',
  ROL_PERMISOS_INVALIDOS: 'Algunos botones no pertenecen a las pantallas elegidas o no están disponibles',

  // Usuarios de la empresa
  USUARIOS_OK: 'Usuarios obtenidos correctamente',
  USUARIO_CREADO: 'Usuario creado correctamente',
  USUARIO_ACTUALIZADO: 'Usuario actualizado correctamente',
  USUARIO_ESTADO_OK: 'Estado del usuario actualizado',
  USUARIO_NO_ENCONTRADO: 'Usuario no encontrado en tu empresa',
  EMPRESA_REQUERIDA: 'Elige la empresa del usuario',
  USUARIO_PROPIO: 'No puedes cambiar tu propio estado ni tu propio rol',
  ROL_NO_ASIGNABLE: 'Ese rol no está disponible para tu empresa',
  PROFESIONAL_REQUERIDO: 'Este rol solo ve sus propias citas: el usuario debe ser profesional de la empresa',
  PROFESIONAL_NO_ENCONTRADO_EMPRESA: 'El profesional no existe o no pertenece a tu empresa',
  CLAVE_RESTABLECIDA: 'Se generó una nueva clave temporal',

  // Categorías de negocio y cargos
  CATEGORIAS_OK: 'Categorías obtenidas correctamente',
  CATEGORIA_GUARDADA: 'Categoría guardada correctamente',
  CATEGORIA_ESTADO_OK: 'Estado de la categoría actualizado',
  CATEGORIA_NO_ENCONTRADA: 'Categoría no encontrada',
  CATEGORIA_CODIGO_DUPLICADO: 'Ya existe una categoría con ese código',
  CATEGORIA_PADRE_INVALIDA: 'La categoría general debe existir y no puede ser a su vez una subcategoría',
  CATEGORIA_CON_SUBCATEGORIAS: 'Esta categoría tiene subcategorías: no puede convertirse en subcategoría',
  CATEGORIA_REGISTRO_INVALIDA: 'Elige un tipo de negocio válido',
  CARGO_GUARDADO: 'Cargo guardado correctamente',
  CARGO_ESTADO_OK: 'Estado del cargo actualizado',
  CARGO_NO_ENCONTRADO: 'Cargo no encontrado',
  CARGO_CODIGO_DUPLICADO: 'Ya existe un cargo con ese código',
  CARGO_NO_ASIGNABLE: 'Ese cargo no corresponde al tipo de negocio de la empresa',
  ROL_PROPIO_NO_APLICA:
    'Tu tipo de negocio no reserva personas: un rol no puede ver solo las citas propias de un profesional',
  // Catálogos
  CATALOGOS_OK: 'Catálogos obtenidos correctamente',
  CATALOGO_NO_ENCONTRADO: 'Catálogo no encontrado',
  CATALOGO_ITEM_GUARDADO: 'Valor del catálogo guardado correctamente',
  CATALOGO_ITEM_ESTADO_OK: 'Estado del valor actualizado',
  CATALOGO_ITEM_NO_ENCONTRADO: 'Valor del catálogo no encontrado',
  CATALOGO_ITEM_DUPLICADO: 'Ya existe un valor con ese código en el catálogo',
  // Documentos
  DOCUMENTO_SUBIDO: 'Archivo subido correctamente',
  DOCUMENTO_NO_ENCONTRADO: 'Archivo no encontrado',
  DOCUMENTO_REQUERIDO: 'Adjunta un archivo',
  DOCUMENTO_TIPO_INVALIDO: 'El tipo de documento no es válido',
  DOCUMENTO_FORMATO_INVALIDO: 'El archivo no tiene un formato permitido para este documento',
  DOCUMENTO_DEMASIADO_GRANDE: (maximoMb) => `El archivo supera el máximo de ${maximoMb} MB`,
  ALMACENAMIENTO_NO_DISPONIBLE: 'El almacenamiento de archivos no está disponible. Intenta más tarde',
  // Cobros
  COBROS_OK: 'Medios de cobro obtenidos correctamente',
  POLITICA_COBRO_GUARDADA: 'Política de cobro actualizada',
  MEDIO_COBRO_GUARDADO: 'Medio de cobro guardado correctamente',
  MEDIO_COBRO_ESTADO_OK: 'Estado del medio de cobro actualizado',
  MEDIO_COBRO_NO_ENCONTRADO: 'Medio de cobro no encontrado',
  MEDIO_COBRO_ENTIDAD_INVALIDA: 'Elige un banco o una billetera válida para este tipo de cobro',
  MEDIO_COBRO_TIPO_CUENTA_REQUERIDO: 'Elige el tipo de cuenta (ahorros o corriente)',
  MEDIO_COBRO_QR_INVALIDO: 'El QR debe ser una imagen subida por tu empresa',
  SOLO_PROFESIONALES: 'Esta opción es solo para profesionales de la empresa',
  // Perfil
  PERFIL_OK: 'Perfil obtenido correctamente',
  PERFIL_ACTUALIZADO: 'Tus datos se actualizaron correctamente',
  CORREO_ACTUALIZADO: 'Tu correo se actualizó. Desde ahora ingresas con el nuevo',
  CORREO_IGUAL: 'El correo nuevo es igual al actual',
  PROFESIONAL_NO_APLICA: 'En este tipo de negocio no se reservan personas: el usuario no puede ser profesional',
};
